# Generated by Django 5.0.1 on 2024-01-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_employee_name_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(blank=True),
        ),
    ]
